### PR TITLE
Handle special characters

### PR DESCRIPTION
**Pull request by renatomariscal**
Adds support to special characters, fixing the bug https://github.com/jvilk/MakeTypes/issues/4.

I haven't yet added unit tests, just tested for my local usage for now.

### CODE REVIEW

**Comment by jvilk** [comment]
Thanks for the contribution!

>I haven't yet added unit tests, just tested for my local usage for now.

Does this mean you aren't interested in adding unit tests, or that you plan to add them later? :)

**Comment by renatomariscal** [comment]
I plan to add later, unless someone does it first 😹

**Comment by giulianok** [comment]
Screen Shot 2021-07-08 at 9 01 46 PM

very needed! how can I help?

**Comment by renatomariscal** [comment]
@giulianok for this PR to be acceptable, I am missing unit tests.
My focus has been far from this for a long time.

You can collaborate adding the unit tests / take over / or work directly from this branch to unblock your dependent work.

**Comment by RobertjanTuit** [comment]
Looks like I might have duplicated some work :) But here is a fix with partial tests:  https://github.com/jvilk/MakeTypes/pull/26

**Comment by renatomariscal** [comment]
Closing due inactivity and duplication.

**Pull request closed without merging**
